import Shipment from '../models/Shipment.js';
import Booking from '../models/Booking.js';

// @desc    Get all shipments
// @route   GET /api/shipments
// @access  Public
export const getShipments = async (req, res) => {
  try {
    const { status, createdBy } = req.query;
    const query = {};

    if (status) {
      query.status = status;
    }
    if (createdBy) {
      query.createdBy = createdBy;
    }

    const shipments = await Shipment.find(query)
      .populate('createdBy', 'name phone')
      .sort({ createdAt: -1 });

    // Ensure shipments have shipmentId (for existing shipments without it)
    // Only update if missing to avoid unnecessary writes
    const shipmentsNeedingId = shipments.filter(s => !s.shipmentId);
    if (shipmentsNeedingId.length > 0) {
      const existingCount = await Shipment.countDocuments({ shipmentId: { $exists: true } });
      for (let i = 0; i < shipmentsNeedingId.length; i++) {
        shipmentsNeedingId[i].shipmentId = `SH${String(existingCount + i + 1).padStart(2, '0')}`;
        await shipmentsNeedingId[i].save();
      }
      // Re-fetch to get updated shipmentIds
      const updatedShipments = await Shipment.find(query)
        .populate('createdBy', 'name phone')
        .sort({ createdAt: -1 });
      shipments.splice(0, shipments.length, ...updatedShipments);
    }

    // Get booking status for each shipment
    const shipmentIds = shipments.map(s => s._id);
    const activeBookings = await Booking.find({
      shipmentId: { $in: shipmentIds },
      status: { $in: ['Pending', 'Approved'] },
    }).populate('userId', 'name');

    // Create a map of shipmentId -> booking
    const bookingMap = {};
    activeBookings.forEach(booking => {
      bookingMap[booking.shipmentId.toString()] = {
        isBooked: true,
        bookedBy: booking.userName,
        bookingStatus: booking.status,
        bookingId: booking._id,
      };
    });

    // Add booking status to each shipment
    const shipmentsWithBookingStatus = shipments.map(shipment => {
      const bookingInfo = bookingMap[shipment._id.toString()];
      return {
        ...shipment.toObject(),
        isBooked: bookingInfo ? true : false,
        bookedBy: bookingInfo?.bookedBy || null,
        bookingStatus: bookingInfo?.bookingStatus || null,
      };
    });

    res.json(shipmentsWithBookingStatus);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get single shipment
// @route   GET /api/shipments/:id
// @access  Public
export const getShipmentById = async (req, res) => {
  try {
    const shipment = await Shipment.findById(req.params.id).populate(
      'createdBy',
      'name phone vehicleNumber'
    );

    if (shipment) {
      res.json(shipment);
    } else {
      res.status(404).json({ message: 'Shipment not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create new shipment
// @route   POST /api/shipments
// @access  Private
export const createShipment = async (req, res) => {
  try {
    const {
      origin,
      destination,
      vehicleType,
      load,
      weight,
      date,
      eta,
      driver,
      coordinates,
      image,
    } = req.body;

    // Handle file upload if present
    let imagePath = '';
    if (req.file) {
      imagePath = `/uploads/${req.file.filename}`;
    } else if (image) {
      // If image is sent as base64 or URL, use it directly
      imagePath = image;
    }

    // Validate required fields
    if (!origin || !destination || !vehicleType || !load || !weight || !date) {
      return res.status(400).json({ 
        message: 'Missing required fields',
        required: ['origin', 'destination', 'vehicleType', 'load', 'weight', 'date'],
        received: { origin, destination, vehicleType, load, weight, date }
      });
    }

    // Validate weight is a number
    const weightNum = parseFloat(weight);
    if (isNaN(weightNum) || weightNum <= 0) {
      return res.status(400).json({ 
        message: 'Weight must be a positive number',
        received: weight
      });
    }

    // Validate date
    const dateObj = date ? new Date(date) : new Date();
    if (isNaN(dateObj.getTime())) {
      return res.status(400).json({ 
        message: 'Invalid date format',
        received: date
      });
    }

    // Create shipment - shipmentId will be auto-generated by pre-save hook
    const shipment = await Shipment.create({
      origin: origin.trim(),
      destination: destination.trim(),
      vehicleType: vehicleType.trim(),
      load: load.trim(),
      weight: weightNum,
      date: dateObj,
      eta: eta ? eta.trim() : '',
      driver,
      coordinates,
      image: imagePath,
      createdBy: req.user._id,
      status: req.body.status || 'Pending',
      price: 0, // Default price since it's no longer required
    });

    // Ensure shipmentId is generated (in case pre-save hook didn't run)
    if (!shipment.shipmentId) {
      try {
        // Find all shipments with SH## format and get the highest number
        const existingShipments = await Shipment.find({ 
          shipmentId: { $exists: true, $regex: /^SH\d+$/ } 
        }).select('shipmentId').lean();
        
        let nextNumber = 1;
        if (existingShipments.length > 0) {
          // Extract numbers and find the max
          const numbers = existingShipments
            .map(s => {
              const match = s.shipmentId?.match(/^SH(\d+)$/);
              return match ? parseInt(match[1], 10) : 0;
            })
            .filter(n => n > 0);
          
          if (numbers.length > 0) {
            nextNumber = Math.max(...numbers) + 1;
          }
        }
        
        shipment.shipmentId = `SH${String(nextNumber).padStart(2, '0')}`;
        await shipment.save();
      } catch (saveError) {
        console.error('Error saving shipmentId:', saveError);
        // Continue even if save fails - shipment is already created
      }
    }

    const populatedShipment = await Shipment.findById(shipment._id).populate(
      'createdBy',
      'name phone vehicleNumber'
    );

    res.status(201).json(populatedShipment);
  } catch (error) {
    console.error('Shipment creation error:', error);
    console.error('Error details:', {
      name: error.name,
      message: error.message,
      code: error.code,
      keyPattern: error.keyPattern,
      keyValue: error.keyValue,
      errors: error.errors,
      stack: error.stack
    });
    
    // Handle duplicate key error (shipmentId)
    if (error.code === 11000) {
      if (error.keyPattern && error.keyPattern.shipmentId) {
        return res.status(400).json({ 
          message: `Shipment ID ${error.keyValue?.shipmentId || 'already exists'}. Please try again.`,
          error: 'Duplicate shipment ID',
          code: 'DUPLICATE_SHIPMENT_ID'
        });
      }
    }
    
    // Handle validation errors
    if (error.name === 'ValidationError') {
      const validationErrors = {};
      Object.keys(error.errors).forEach(key => {
        validationErrors[key] = error.errors[key].message;
      });
      return res.status(400).json({ 
        message: 'Validation error',
        errors: validationErrors,
        code: 'VALIDATION_ERROR'
      });
    }
    
    res.status(500).json({ 
      message: error.message || 'Failed to create shipment',
      error: process.env.NODE_ENV === 'development' ? error.stack : undefined,
      code: 'INTERNAL_ERROR'
    });
  }
};

// @desc    Update shipment
// @route   PUT /api/shipments/:id
// @access  Private
export const updateShipment = async (req, res) => {
  try {
    const shipment = await Shipment.findById(req.params.id);

    if (!shipment) {
      return res.status(404).json({ message: 'Shipment not found' });
    }

    // Check if user is admin or created the shipment
    if (req.user.role !== 'admin' && shipment.createdBy.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to update this shipment' });
    }

    // Handle file upload if present
    const updateData = { ...req.body };
    if (req.file) {
      updateData.image = `/uploads/${req.file.filename}`;
    } else if (req.body.image) {
      updateData.image = req.body.image;
    }

    const updatedShipment = await Shipment.findByIdAndUpdate(
      req.params.id,
      updateData,
      {
        new: true,
        runValidators: true,
      }
    ).populate('createdBy', 'name phone vehicleNumber');

    res.json(updatedShipment);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Delete shipment
// @route   DELETE /api/shipments/:id
// @access  Private/Admin
export const deleteShipment = async (req, res) => {
  try {
    const shipment = await Shipment.findById(req.params.id);

    if (!shipment) {
      return res.status(404).json({ message: 'Shipment not found' });
    }

    await shipment.deleteOne();

    res.json({ message: 'Shipment removed' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get available shipments (not delivered or cancelled)
// @route   GET /api/shipments/available
// @access  Public
export const getAvailableShipments = async (req, res) => {
  try {
    const shipments = await Shipment.find({
      status: { $nin: ['Delivered', 'Cancelled'] },
    })
      .populate('createdBy', 'name phone vehicleNumber')
      .sort({ createdAt: -1 });

    // Ensure shipments have shipmentId (for existing shipments without it)
    const shipmentsNeedingId = shipments.filter(s => !s.shipmentId);
    if (shipmentsNeedingId.length > 0) {
      const existingCount = await Shipment.countDocuments({ shipmentId: { $exists: true } });
      for (let i = 0; i < shipmentsNeedingId.length; i++) {
        shipmentsNeedingId[i].shipmentId = `SH${String(existingCount + i + 1).padStart(2, '0')}`;
        await shipmentsNeedingId[i].save();
      }
      // Re-fetch to get updated shipmentIds
      const updatedShipments = await Shipment.find({
        status: { $nin: ['Delivered', 'Cancelled'] },
      })
        .populate('createdBy', 'name phone vehicleNumber')
        .sort({ createdAt: -1 });
      shipments.splice(0, shipments.length, ...updatedShipments);
    }

    // Get booking status for each shipment
    const shipmentIds = shipments.map(s => s._id);
    const activeBookings = await Booking.find({
      shipmentId: { $in: shipmentIds },
      status: { $in: ['Pending', 'Approved'] },
    }).populate('userId', 'name');

    // Create a map of shipmentId -> booking
    const bookingMap = {};
    activeBookings.forEach(booking => {
      bookingMap[booking.shipmentId.toString()] = {
        isBooked: true,
        bookedBy: booking.userName,
        bookingStatus: booking.status,
        bookingId: booking._id,
      };
    });

    // Add booking status to each shipment
    const shipmentsWithBookingStatus = shipments.map(shipment => {
      const bookingInfo = bookingMap[shipment._id.toString()];
      return {
        ...shipment.toObject(),
        isBooked: bookingInfo ? true : false,
        bookedBy: bookingInfo?.bookedBy || null,
        bookingStatus: bookingInfo?.bookingStatus || null,
      };
    });

    res.json(shipmentsWithBookingStatus);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

